/**
 * Convert an image into mono ASCII art for the startup splash.
 * Uses ffmpeg (decode + scale to a terminal grid) -> luminance -> ASCII ramp.
 *
 *   bun run scripts/make-splash.ts <image> [--width N] [--invert] [--write]
 *
 * Without --write it only previews to stdout. With --write it emits
 * src/assets/splash-art.ts (the static art the binary ships).
 */
import { spawnSync } from "bun";

const args = process.argv.slice(2);
const image = args.find((a) => !a.startsWith("--"));
const width = Number(args[args.indexOf("--width") + 1]) || 72;
const invert = args.includes("--invert");
const write = args.includes("--write");

if (!image) {
  console.error("usage: bun run scripts/make-splash.ts <image> [--width N] [--invert] [--write]");
  process.exit(1);
}

// Dark -> light. Space reads as the (dark) terminal background.
const RAMP = " .:-=+*#%@";

function dimensions(path: string): { w: number; h: number } {
  const probe = spawnSync([
    "ffprobe", "-v", "error", "-select_streams", "v:0",
    "-show_entries", "stream=width,height", "-of", "csv=p=0", path,
  ]);
  const out = probe.stdout.toString().trim();
  const [w, h] = out.split(",").map(Number);
  if (!w || !h) {
    console.error("could not read image dimensions (is ffprobe/ffmpeg installed?)");
    process.exit(1);
  }
  return { w, h };
}

function rawGray(path: string, cols: number, rows: number): Uint8Array {
  const ff = spawnSync([
    "ffmpeg", "-v", "error", "-i", path,
    "-vf", `scale=${cols}:${rows}`, "-pix_fmt", "gray", "-f", "rawvideo", "-",
  ]);
  if (!ff.success) {
    console.error("ffmpeg failed:", ff.stderr.toString());
    process.exit(1);
  }
  return new Uint8Array(ff.stdout);
}

const { w, h } = dimensions(image);
// Terminal cells are ~twice as tall as wide, so halve the row count.
const rows = Math.max(1, Math.round((width * h) / w / 2));
const px = rawGray(image, width, rows);

const lines: string[] = [];
for (let y = 0; y < rows; y++) {
  let line = "";
  for (let x = 0; x < width; x++) {
    const lum = px[y * width + x] ?? 0;
    const level = invert ? 255 - lum : lum;
    const idx = Math.min(RAMP.length - 1, Math.floor((level / 255) * RAMP.length));
    line += RAMP[idx] ?? " ";
  }
  lines.push(line.replace(/\s+$/, "")); // trim trailing blanks (terminal bg)
}

// Drop fully-blank top/bottom rows so the art sits tight.
while (lines.length && lines[0]!.trim() === "") lines.shift();
while (lines.length && lines[lines.length - 1]!.trim() === "") lines.pop();

console.log(`# ${image}  ${width}x${rows}${invert ? "  (inverted)" : ""}\n`);
console.log(lines.join("\n"));

if (write) {
  const body =
    `/** Generated by scripts/make-splash.ts — do not edit by hand. */\n` +
    `export const SPLASH_ART: readonly string[] = [\n` +
    lines.map((l) => `  ${JSON.stringify(l)},`).join("\n") +
    `\n];\n`;
  await Bun.write("src/assets/splash-art.ts", body);
  console.log(`\nwrote src/assets/splash-art.ts (${lines.length} rows)`);
}
